apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/esmacancs/rook-ceph.git'
    targetRevision: main
    path: overlays/prod
    kustomize:
      namePrefix: ""
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
