apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.7
  dataDirHostPath: /var/lib/rook

  mon:
    count: 3
    allowMultiplePerNode: false
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - storage-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  mgr:
    count: 2
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - storage-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

  network:
    provider: host
    public:
      network: 10.8.132.160/27   # VLAN 3409 - Ceph Public
    cluster:
      network: 10.8.132.128/27   # VLAN 3408 - Ceph Cluster

  storage:
    useAllNodes: false
    nodes:
      - name: worker-comp-ceph-01
        devices:
          - name: "pci-0000:65:00.0-scsi-0:3:105:0" # sdd
          - name: "pci-0000:65:00.0-scsi-0:3:106:0" # sde
          - name: "pci-0000:65:00.0-scsi-0:3:108:0" # sdg
          - name: "pci-0000:65:00.0-scsi-0:3:109:0" # sdh
          - name: "pci-0000:65:00.0-scsi-0:3:110:0" # sdi
          - name: "pci-0000:65:00.0-scsi-0:3:111:0" # sdj

      - name: worker-comp-ceph-02
        devices:
          - name: "pci-0000:18:00.0-scsi-0:2:11:0"  # sdl
          - name: "pci-0000:18:00.0-scsi-0:2:12:0"  # sdm
          - name: "pci-0000:18:00.0-scsi-0:2:13:0"  # sdn
          - name: "pci-0000:18:00.0-scsi-0:2:14:0"  # sdo
          - name: "pci-0000:18:00.0-scsi-0:2:15:0"  # sdp
          - name: "pci-0000:18:00.0-scsi-0:2:16:0"  # sdr
          - name: "pci-0000:18:00.0-scsi-0:2:17:0"  # sds
          - name: "pci-0000:18:00.0-scsi-0:2:18:0"  # sdr
          - name: "pci-0000:18:00.0-scsi-0:2:19:0"  # sdt
          - name: "pci-0000:18:00.0-scsi-0:2:2:0"   # sdc

      - name: worker-comp-ceph-03
        devices:
          - name: "pci-0000:65:00.0-scsi-0:3:105:0" # sdb
          - name: "pci-0000:65:00.0-scsi-0:3:106:0" # sdc
          - name: "pci-0000:65:00.0-scsi-0:3:107:0" # sdd
          - name: "pci-0000:65:00.0-scsi-0:3:108:0" # sde
          - name: "pci-0000:65:00.0-scsi-0:3:109:0" # sdf
          - name: "pci-0000:65:00.0-scsi-0:3:110:0" # sdg
          - name: "pci-0000:65:00.0-scsi-0:3:111:0" # sdi

  crashCollector:
    disable: false

  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - storage-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
