apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.7
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
  dashboard:
    enabled: true
    ssl: true
  network:
    provider: host
    public:
      network: 10.8.132.160/27   # Ceph Public VLAN
    cluster:
      network: 10.8.132.128/27   # Ceph Cluster VLAN
#  storage:
#    useAllNodes: false
#    nodes: []  # overridden in overlays/prod/rook-ceph-overrides.yaml
  crashCollector:
    disable: false
